name = "agent-gateway-api-open4dev"
main = "src/worker.ts"
compatibility_date = "2026-03-12"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[routes]]
pattern = "api.tongateway.ai"
custom_domain = true

[vars]
TON_BROADCAST_URL = "https://testnet.toncenter.com/api/v2/sendBoc"
TON_API_KEY_HEADER = "X-API-Key"

[[kv_namespaces]]
binding = "PENDING_STORE"
id = "106e5c801af7479096cf2252764feef5"
